#!/bin/sh -e

HTS_USER="hts"

case "$1" in
purge)
    # Clean up webgrab data directory
    if getent passwd "$HTS_USER" >/dev/null; then
        HTS_HOMEDIR="$(getent passwd "$HTS_USER" | cut -d':' -f6)"
        rm -rf "$HTS_HOMEDIR/webgrab" || true
    fi
    ;;
esac

exit 0
