#!/bin/sh -e

HTS_USER="hts"

. /usr/share/debconf/confmodule
db_version 2.0

case "$1" in
purge)
    if getent passwd "$HTS_USER" >/dev/null; then
        rm -rf "$(getent passwd "$HTS_USER" | cut -d':' -f6)"
        deluser --system "$HTS_USER"
    fi

    # Clean up additional directories from tvheadend-full
    rm -rf /etc/tvheadend || true
    rm -rf /var/log/tvheadend || true

    db_purge
   ;;
esac

#DEBHELPER#

exit 0
