#!/bin/sh -e

HTS_USER="hts"

case "$1" in
purge|remove)
    # Remove picons symlink if it exists
    if getent passwd "$HTS_USER" >/dev/null; then
        HTS_HOMEDIR="$(getent passwd "$HTS_USER" | cut -d':' -f6)"
        rm -f "$HTS_HOMEDIR/picons" || true
    fi
    ;;
esac

exit 0
