name: Build TVHeadend Packages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo docker system prune -af
          df -h

      - name: Build FFmpeg and libvpl dependencies
        run: |
          chmod +x build-dependencies.sh
          ./build-dependencies.sh

      - name: Build TVHeadend packages
        run: |
          chmod +x build-tvheadend.sh
          ./build-tvheadend.sh

      - name: List built packages
        run: |
          echo "Built packages:"
          ls -lh output/
          echo ""
          echo "Package details:"
          for deb in output/*.deb; do
            echo "=== $(basename $deb) ==="
            dpkg-deb -I "$deb" | grep -E "(Package|Version|Architecture|Installed-Size)"
            echo ""
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tvheadend-debian-packages-${{ github.sha }}
          path: output/*.deb
          retention-days: 30

      - name: Checkout gh-pages branch
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Create apt repository
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          # Install required tools
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

          # Get architecture from packages
          ARCH=$(dpkg-deb -f output/tvheadend_*.deb Architecture)

          # Create repository structure in gh-pages
          mkdir -p gh-pages/debian/pool/main

          # Copy TVHeadend packages
          cp output/*.deb gh-pages/debian/pool/main/

          # Copy FFmpeg and libvpl dependency packages
          cp custom-libs/*.deb gh-pages/debian/pool/main/

          # Create Packages file for each architecture
          cd gh-pages/debian

          # Scan packages
          dpkg-scanpackages --arch ${ARCH} pool/ > Packages
          dpkg-scanpackages --arch all pool/ >> Packages
          gzip -k -f Packages

          # Create Release file
          cat > Release <<EOF
          Origin: TVHeadend HWAccel Builder
          Label: tvheadend-hwaccel
          Suite: stable
          Codename: stable
          Architectures: ${ARCH} all
          Components: main
          Description: TVHeadend with hardware acceleration support
          Date: $(date -R)
          EOF

          # Add file checksums to Release
          echo "MD5Sum:" >> Release
          md5sum Packages Packages.gz | awk '{print " " $1 " " $2}' >> Release
          echo "SHA256:" >> Release
          sha256sum Packages Packages.gz | awk '{print " " $1 " " $2}' >> Release

          cd ../..

      - name: Create installation instructions
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          cat > gh-pages/README.md <<'EOF'
          # TVHeadend Hardware Acceleration Packages

          This repository provides Debian packages for TVHeadend with hardware acceleration support (VAAPI, NVENC, QSV).

          ## Installation

          Add the repository to your system:

          ```bash
          # Add the repository
          echo "deb [trusted=yes] https://$(echo ${{ github.repository }} | cut -d'/' -f1).github.io/$(echo ${{ github.repository }} | cut -d'/' -f2)/debian/ stable main" | sudo tee /etc/apt/sources.list.d/tvheadend-hwaccel.list

          # Update package list
          sudo apt-get update
          ```

          ## Available Packages

          - **tvheadend** - Core TV streaming server
          - **tvheadend-comskip** - Commercial detection tools
          - **tvheadend-picons** - Channel icons
          - **tvheadend-webgrab** - EPG grabber
          - **tvheadend-full** - Meta-package (installs all components)

          ## Install Options

          ### Full Installation
          ```bash
          sudo apt-get install tvheadend-full
          ```

          ### Core Only
          ```bash
          sudo apt-get install tvheadend
          ```

          ### Custom Selection
          ```bash
          sudo apt-get install tvheadend tvheadend-comskip tvheadend-picons
          ```

          ## Manual Download

          You can also download .deb files directly from the [Releases](https://github.com/${{ github.repository }}/releases) page.
          EOF

      - name: Publish to GitHub Pages
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update apt repository" && git push)

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: output/*.deb
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
