name: Build TVHeadend Packages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo docker system prune -af
          df -h

      - name: Build FFmpeg and libvpl dependencies
        run: |
          chmod +x build-dependencies.sh
          ./build-dependencies.sh
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}

      - name: Build TVHeadend packages
        run: |
          chmod +x build-tvheadend.sh
          ./build-tvheadend.sh
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}

      - name: List built packages
        run: |
          echo "Built packages:"
          ls -lh output/
          echo ""
          echo "Package details:"
          for deb in output/*.deb; do
            echo "=== $(basename $deb) ==="
            dpkg-deb -I "$deb" | grep -E "(Package|Version|Architecture|Installed-Size)"
            echo ""
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tvheadend-debian-packages-${{ matrix.arch }}-${{ github.sha }}
          path: output/*.deb
          retention-days: 30

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: tvheadend-debian-packages-*

      - name: Create apt repository
        run: |
          # Install required tools
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

          # Create repository structure in gh-pages
          mkdir -p gh-pages/debian/pool/main

          # Copy all packages from artifacts
          find artifacts -name "*.deb" -exec cp {} gh-pages/debian/pool/main/ \;

          # List what we have
          echo "Packages in repository:"
          ls -lh gh-pages/debian/pool/main/

          # Create Packages file for each architecture
          cd gh-pages/debian

          # Scan packages for both architectures
          dpkg-scanpackages --arch amd64 pool/ > Packages
          dpkg-scanpackages --arch arm64 pool/ >> Packages
          dpkg-scanpackages --arch all pool/ >> Packages
          gzip -k -f Packages

          # Create Release file
          cat > Release <<EOF
          Origin: TVHeadend HWAccel Builder
          Label: tvheadend-hwaccel
          Suite: stable
          Codename: stable
          Architectures: amd64 arm64 all
          Components: main
          Description: TVHeadend with hardware acceleration support
          Date: $(date -R)
          EOF

          # Add file checksums to Release
          echo "MD5Sum:" >> Release
          md5sum Packages Packages.gz | awk '{print " " $1 " " $2}' >> Release
          echo "SHA256:" >> Release
          sha256sum Packages Packages.gz | awk '{print " " $1 " " $2}' >> Release

          cd ../..

      - name: Create installation instructions
        run: |
          # Get build date
          BUILD_DATE=$(date -R)

          # Start README with badges
          cat > gh-pages/README.md <<EOF
          # TVHeadend Hardware Acceleration Packages

          ![Build Status](https://github.com/${{ github.repository }}/actions/workflows/build.yml/badge.svg)
          ![Docker Build](https://github.com/${{ github.repository }}/actions/workflows/docker.yml/badge.svg)
          ![GitHub release](https://img.shields.io/github/v/release/${{ github.repository }}?include_prereleases)
          ![TVHeadend](https://img.shields.io/badge/TVHeadend-4.3--dev-orange)
          ![Architectures](https://img.shields.io/badge/arch-amd64%20%7C%20arm64-blue)
          ![FFmpeg](https://img.shields.io/badge/FFmpeg-7.1.2-green)
          ![libvpl](https://img.shields.io/badge/libvpl-2.15.0-green)
          ![License](https://img.shields.io/github/license/${{ github.repository }})

          This repository provides Debian packages for TVHeadend with hardware acceleration support (VAAPI, NVENC, QSV).

          **Last Updated:** ${BUILD_DATE}
          **Architectures:** amd64, arm64, all

          ## Quick Start

          Add the repository to your Debian/Ubuntu system:

          \`\`\`bash
          # Add the repository
          echo "deb [trusted=yes] https://$(echo ${{ github.repository }} | cut -d'/' -f1).github.io/$(echo ${{ github.repository }} | cut -d'/' -f2)/debian/ stable main" | sudo tee /etc/apt/sources.list.d/tvheadend-hwaccel.list

          # Update package list
          sudo apt-get update

          # Install full suite
          sudo apt-get install tvheadend-full
          \`\`\`

          ## Available Packages

          ### TVHeadend Packages

          EOF

          # Add TVHeadend package information from repository
          for deb in gh-pages/debian/pool/main/tvheadend*.deb; do
            if [ -f "$deb" ]; then
              PACKAGE=$(dpkg-deb -f "$deb" Package)
              VERSION=$(dpkg-deb -f "$deb" Version)
              PKG_ARCH=$(dpkg-deb -f "$deb" Architecture)
              DESCRIPTION=$(dpkg-deb -f "$deb" Description | head -n1)
              SIZE=$(ls -lh "$deb" | awk '{print $5}')

              cat >> gh-pages/README.md <<EOF
          #### ${PACKAGE}
          - **Version:** ${VERSION}
          - **Architecture:** ${PKG_ARCH}
          - **Size:** ${SIZE}
          - **Description:** ${DESCRIPTION}

          EOF
            fi
          done

          # Add dependency packages information
          cat >> gh-pages/README.md <<'EOF'
          ### Dependency Packages (FFmpeg & libvpl)

          These packages are automatically installed as dependencies:

          EOF

          for deb in gh-pages/debian/pool/main/{ffmpeg,libvpl}*.deb; do
            if [ -f "$deb" ]; then
              PACKAGE=$(dpkg-deb -f "$deb" Package)
              VERSION=$(dpkg-deb -f "$deb" Version)
              PKG_ARCH=$(dpkg-deb -f "$deb" Architecture)
              SIZE=$(ls -lh "$deb" | awk '{print $5}')

              cat >> gh-pages/README.md <<EOF
          - **${PACKAGE}** (${VERSION}) - ${PKG_ARCH}, ${SIZE}
          EOF
            fi
          done

          # Add installation instructions
          cat >> gh-pages/README.md <<'EOF'

          ## Installation Options

          ### Full Installation (Recommended)
          Installs TVHeadend with all optional components:

          \`\`\`bash
          sudo apt-get install tvheadend-full
          \`\`\`

          This includes:
          - TVHeadend core server
          - Comskip (commercial detection)
          - Picons (channel icons)
          - WebGrab++ (EPG grabber)

          ### Core Only
          Minimal installation with just the TVHeadend server:

          \`\`\`bash
          sudo apt-get install tvheadend
          \`\`\`

          ### Custom Selection
          Pick and choose components:

          \`\`\`bash
          # Core + commercial detection
          sudo apt-get install tvheadend tvheadend-comskip

          # Core + channel icons
          sudo apt-get install tvheadend tvheadend-picons

          # Core + EPG grabber
          sudo apt-get install tvheadend tvheadend-webgrab
          \`\`\`

          ## Hardware Acceleration Support

          The packages include support for:

          - **VAAPI** - Intel/AMD GPU acceleration
          - **NVENC/NVDEC** - NVIDIA GPU encoding/decoding
          - **QSV** - Intel Quick Sync Video
          - **VDPAU** - NVIDIA video decoding (legacy)

          ## Package Details

          ### tvheadend
          Core TV streaming server with:
          - Multi-format recording (TS, Matroska, MP4)
          - Hardware-accelerated transcoding
          - Web interface on port 9981
          - HTSP streaming on port 9982
          - EPG support
          - DVB, IPTV, SAT>IP, and HDHomeRun support

          ### tvheadend-comskip
          Commercial detection suite:
          - **comskip** - Detects commercials in recordings
          - **comchap** - Adds chapter markers at commercial breaks
          - **comcut** - Removes commercials from recordings

          ### tvheadend-picons
          Channel icon library (~65MB):
          - SNP format (Service Name Picons)
          - SRP format (Service Reference Picons)
          - Automatically linked to TVHeadend

          ### tvheadend-webgrab
          EPG data grabber:
          - WebGrab++ v5.3.0
          - tv_grab_wg++ wrapper for TVHeadend integration
          - Supports multiple EPG sources

          ## System Requirements

          - Debian 12 (Bookworm) or Ubuntu 24.04+
          - For hardware acceleration:
            - Intel: i965-va-driver or intel-media-va-driver
            - NVIDIA: nvidia-driver with CUDA support
            - AMD: mesa-va-drivers

          ## Post-Installation

          1. Access web interface: http://your-server-ip:9981
          2. Default credentials: admin / admin (change immediately!)
          3. Configure tuners and networks
          4. Set up EPG sources
          5. Enable hardware acceleration in transcoding profiles

          ## Manual Download

          Download .deb files directly:
          - [GitHub Releases](https://github.com/${{ github.repository }}/releases)
          - [Artifacts from latest build](https://github.com/${{ github.repository }}/actions)

          ## Build Information

          - **Repository:** https://github.com/${{ github.repository }}
          - **CI/CD:** GitHub Actions
          - **Build Time:** ~26 minutes
          - **Source:**
            - TVHeadend: [tvheadend/tvheadend](https://github.com/tvheadend/tvheadend)
            - FFmpeg: 7.1.2 (Debian packaging)
            - libvpl: 2.15.0 (Intel Video Processing Library)

          ## Support

          - [Report Issues](https://github.com/${{ github.repository }}/issues)
          - [TVHeadend Documentation](https://tvheadend.org/projects/tvheadend/wiki)
          - [TVHeadend Forums](https://tvheadend.org/d/)
          EOF

      - name: Publish to GitHub Pages
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update apt repository [skip ci]" && git push)
