name: Build TVHeadend Packages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo docker system prune -af
          df -h

      - name: Build packages
        run: |
          chmod +x build-tvheadend.sh
          ./build-tvheadend.sh

      - name: List built packages
        run: |
          echo "Built packages:"
          ls -lh output/
          echo ""
          echo "Package details:"
          for deb in output/*.deb; do
            echo "=== $(basename $deb) ==="
            dpkg-deb -I "$deb" | grep -E "(Package|Version|Architecture|Installed-Size)"
            echo ""
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tvheadend-debian-packages-${{ github.sha }}
          path: output/*.deb
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: output/*.deb
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
